@AbapCatalog.viewEnhancementCategory: [#PROJECTION_LIST, #UNION ]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Source List - Consumption View'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType: {serviceQuality: #A, sizeCategory: #S, dataClass: #MASTER}
@VDM.viewType: #CONSUMPTION
@ObjectModel.supportedCapabilities: [ #SQL_DATA_SOURCE, #CDS_MODELING_DATA_SOURCE, #CDS_MODELING_ASSOCIATION_TARGET ]
define view entity ZC_KX_SourceList_OP
  as select from ZI_KX_SourceList_OP
{
  key Material,
  key SourceListPlant,
  key SourceListRecord,
      MRPSourcingControl,
      ValidityStartDate,
      ValidityEndDate,
      PurchaseOutlineAgreement,
      PurchaseOutlineAgreementItem,
      PurchasingOrganization,
      ManufacturerMaterial,
      PurOutlineAgreementIsFixed,
      SupplierIsFixed,
      Supplier,
      OrderQuantityUnit,
      SourceOfSupplyIsBlocked,
      SupplyingPlant,
      PurchasingDocumentNumber,
      ItemNumberOfPurchasingDocument,
      RequirementTrackingNumber,
      MRPArea,
      OrderPriceUnit,
      DenominatorForPriceConversion,
      NumeratorForPriceConversion,
      PurchasingDocumentCategory,
      SupplierToBeSupplied,
      NumberOfPurchasingInfoRecord,
      StockType,
      AccountAssignmentCategory,
      SubcontractingSupplier,
      StorageLocation,
      MaterialNumber,
      PurchaseOrderUnitOfMeasure,
      PurchaseOrderQuantity,
      NetPriceInPurchasingDocument,
      TargetQuantity,
      PriceUnit,
      PlannedDeliveryTimeInDays,
      ItemCategoryInPurchasingDoc,
      SpecialStockIndicator,
      DenominatorForUnitConversion,
      NumeratorForUnitConversion,
      GRProcessingTimeInDays,
      Name,
      FactoryCalendar,
      AssemblyScrapPercent,
      ProcurementType,
      LotSizingProcedure,
      FixedLotSizeQuantity,
      MaximumLotSizeQuantity,
      MinimumLotSizeQuantity,
      LotSizeRoundingQuantity,
      InHouseProductionTime,
      PlanningTimeFence,
      PlannedDeliveryDurationInDay,
      ProcurementSubType,
      HasProductionVersion,
      GoodsReceiptDuration,
      BaseUnit,
      StandardPrice,
      SpecialProcurementIndicator,
      TransferPlant,
      QuotaArrangementUsage,
      PlantName,
      PurchInfoRecPlant,
      PurchInfoRecSuppliersAccount,
      PurchInfoRecPlanDelTimeInDays
}
